
with open('naga/front/glsl/variables.py', 'r+') as f:
    content = f.read()
    # Find the start of _extract_format_qualifier
    idx = content.find('def _extract_format_qualifier(self, qualifiers: Any) -> Optional[Any]:')
    if idx == -1:
        print("Could not find anchor!")
        import sys; sys.exit(1)
        
    f.seek(idx)
    f.truncate()
    
    # Write _extract_format_qualifier body reloaded from valid source
    f.write('    def _extract_format_qualifier(self, qualifiers: Any) -> Optional[Any]:\n')
    f.write('        """Extract format qualifier from layout qualifiers."""\n')
    f.write('        # Qualifiers can be a list of tokens or a meta dict with "layout"\n')
    f.write('        if isinstance(qualifiers, dict):\n')
    f.write('            layout = qualifiers.get("layout", {})\n')
    f.write('        else:\n')
    f.write('            # Try to get layout from meta if passed a declaration\n')
    f.write('            meta = getattr(qualifiers, "meta", {})\n')
    f.write('            layout = meta.get("layout", {})\n')
    f.write('            \n')
    f.write('        # Common image formats in GLSL\n')
    f.write('        from ...ir import StorageFormat\n')
    f.write('        formats = {\n')
    f.write('            "rgba32f": StorageFormat.RGBA32FLOAT,\n')
    f.write('            "rgba16f": StorageFormat.RGBA16FLOAT,\n')
    f.write('            "rg32f": StorageFormat.RG32FLOAT,\n')
    f.write('            "rg16f": StorageFormat.RG16FLOAT,\n')
    f.write('            "r32f": StorageFormat.R32FLOAT,\n')
    f.write('            "r16f": StorageFormat.R16FLOAT,\n')
    f.write('            "rgba32ui": StorageFormat.RGBA32UINT,\n')
    f.write('            "rgba16ui": StorageFormat.RGBA16UINT,\n')
    f.write('            "rgba8ui": StorageFormat.RGBA8UINT,\n')
    f.write('            "rg32ui": StorageFormat.RG32UINT,\n')
    f.write('            "rg16ui": StorageFormat.RG16UINT,\n')
    f.write('            "rg8ui": StorageFormat.RG8UINT,\n')
    f.write('            "r32ui": StorageFormat.R32UINT,\n')
    f.write('            "r16ui": StorageFormat.R16UINT,\n')
    f.write('            "r8ui": StorageFormat.R8UINT,\n')
    f.write('            "rgba32i": StorageFormat.RGBA32SINT,\n')
    f.write('            "rgba16i": StorageFormat.RGBA16SINT,\n')
    f.write('            "rgba8i": StorageFormat.RGBA8SINT,\n')
    f.write('            "rg32i": StorageFormat.RG32SINT,\n')
    f.write('            "rg16i": StorageFormat.RG16SINT,\n')
    f.write('            "rg8i": StorageFormat.RG8SINT,\n')
    f.write('            "r32i": StorageFormat.R32SINT,\n')
    f.write('            "r16i": StorageFormat.R16SINT,\n')
    f.write('            "r8i": StorageFormat.R8SINT,\n')
    f.write('            "rgba8": StorageFormat.RGBA8UNORM,\n')
    f.write('            "rgba8_snorm": StorageFormat.RGBA8SNORM,\n')
    f.write('            "bgra8": StorageFormat.BGRA8UNORM,\n')
    f.write('        }\n')
    f.write('        \n')
    f.write('        for key in layout:\n')
    f.write('            if key in formats:\n')
    f.write('                return formats[key]\n')
    f.write('        return None\n\n')

    f.write('    def _is_writeonly_image(self, qualifiers: Any) -> bool:\n')
    f.write('        """Check if image is writeonly."""\n')
    f.write('        from .token import TokenValue\n')
    f.write('        qualifier_values = []\n')
    f.write('        if isinstance(qualifiers, list):\n')
    f.write('            qualifier_values = [t.value for t in qualifiers if hasattr(t, "value")]\n')
    f.write('        \n')
    f.write('        return TokenValue.MEMORY_QUALIFIER in qualifier_values\n\n')

    f.write('    def _create_image_variable(self, name: str, dim: Any, arrayed: bool, ty: Any, format_qualifier: Any, meta: Any) -> Any:\n')
    f.write('        """Create image variable with format qualifier."""\n')
    f.write('        from ...ir import GlobalVariable, AddressSpace, Type, TypeInner, Image\n')
    f.write('        \n')
    f.write('        # Image in NAGA is a TypeInner\n')
    f.write('        image_inner = TypeInner.new_image(\n')
    f.write('            dim=dim,\n')
    f.write('            arrayed=arrayed,\n')
    f.write('            class_info=None # Storage image\n')
    f.write('        )\n')
    f.write('        \n')
    f.write('        return {\n')
    f.write('            "name": name,\n')
    f.write('            "ty": ty,\n')
    f.write('            "format": format_qualifier,\n')
    f.write('            "meta": meta\n')
    f.write('        }\n\n')
    
    f.write('    def get_entry_args(self) -> List[EntryArg]:\n')
    f.write('        """Get entry point arguments."""\n')
    f.write('        return self.entry_args.copy()\n\n')
    
    f.write('    def get_global_variables(self) -> List[GlobalVariableInfo]:\n')
    f.write('        """Get global variables."""\n')
    f.write('        return self.global_variables.copy()\n\n')
    
    f.write('    def get_errors(self) -> List[str]:\n')
    f.write('        """Get variable parsing errors."""\n')
    f.write('        return self.errors.copy()\n\n')
    
    f.write('    def clear_errors(self) -> None:\n')
    f.write('        """Clear variable parsing errors."""\n')
    f.write('        self.errors.clear()\n')
