"""
HLSL reserved keywords.

Contains a set of all reserved HLSL keywords that should not be used
as variable or function names.
"""

from __future__ import annotations

from typing import FrozenSet


# Case-insensitive keywords in FXC (when not in strict mode)
RESERVED_CASE_INSENSITIVE: FrozenSet[str] = frozenset([
    "asm",
    "decl",
    "pass",
    "technique",
    "Texture1D",
    "Texture2D",
    "Texture3D",
    "TextureCube",
])


# Reserved HLSL keywords
# Derived from https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-appendix-keywords
RESERVED_KEYWORD_SET: FrozenSet[str] = frozenset([
    # FXC keywords
    "AppendStructuredBuffer",
    "asm",
    "asm_fragment",
    "BlendState",
    "bool",
    "break",
    "Buffer",
    "ByteAddressBuffer",
    "case",
    "cbuffer",
    "centroid",
    "class",
    "column_major",
    "compile",
    "compile_fragment",
    "CompileShader",
    "const",
    "continue",
    "ComputeShader",
    "ConsumeStructuredBuffer",
    "default",
    "DepthStencilState",
    "DepthStencilView",
    "discard",
    "do",
    "double",
    "DomainShader",
    "dword",
    "else",
    "export",
    "extern",
    "false",
    "float",
    "for",
    "fxgroup",
    "GeometryShader",
    "groupshared",
    "half",
    "Hullshader",
    "if",
    "in",
    "inline",
    "inout",
    "InputPatch",
    "int",
    "interface",
    "line",
    "lineadj",
    "linear",
    "LineStream",
    "matrix",
    "min16float",
    "min10float",
    "min16int",
    "min12int",
    "min16uint",
    "namespace",
    "nointerpolation",
    "noperspective",
    "NULL",
    "out",
    "OutputPatch",
    "packoffset",
    "pass",
    "pixelfragment",
    "PixelShader",
    "point",
    "PointStream",
    "precise",
    "RasterizerState",
    "RenderTargetView",
    "return",
    "register",
    "row_major",
    "RWBuffer",
    "RWByteAddressBuffer",
    "RWStructuredBuffer",
    "RWTexture1D",
    "RWTexture1DArray",
    "RWTexture2D",
    "RWTexture2DArray",
    "RWTexture3D",
    "sample",
    "sampler",
    "SamplerComparisonState",
    "SamplerState",
    "shared",
    "snorm",
    "stateblock",
    "stateblock_state",
    "static",
    "string",
    "struct",
    "switch",
    "tbuffer",
    "technique",
    "technique10",
    "technique11",
    "texture",
    "Texture1D",
    "Texture1DArray",
    "Texture2D",
    "Texture2DArray",
    "Texture2DMS",
    "Texture2DMSArray",
    "Texture3D",
    "TextureCube",
    "TextureCubeArray",
    "true",
    "typedef",
    "uint",
    "uint16_t",
    "uint32_t",
    "uint64_t",
    "unorm",
    "unsigned",
    "vector",
    "vertexshader",
    "void",
    "volatile",
    "while",
    
    # Semantic keywords (system-value and user semantics)
    "SV_ClipDistance",
    "SV_CullDistance",
    "SV_Depth",
    "SV_Depth0",
    "SV_Depth1",
    "SV_DispatchThreadID",
    "SV_DomainLocation",
    "SV_GroupID",
    "SV_GroupIndex",
    "SV_GroupThreadID",
    "SV_GSInstanceID",
    "SV_InstanceID",
    "SV_IsFrontFace",
    "SV_OutputControlPointID",
    "SV_Position",
    "SV_PrimitiveID",
    "SV_RenderTargetArrayIndex",
    "SV_SampleIndex",
    "SV_StencilRef",
    "SV_Target",
    "SV_Target0",
    "SV_Target1",
    "SV_Target2",
    "SV_Target3",
    "SV_Target4",
    "SV_Target5",
    "SV_Target6",
    "SV_Target7",
    "SV_TessFactor",
    "SV_VertexID",
    "SV_ViewID",
    "SV_Coverage",
    "SV_InnerCoverage",
    "SV_Barycentrics",
    "SV_CullPrimitive",
])


__all__ = [
    "RESERVED_CASE_INSENSITIVE",
    "RESERVED_KEYWORD_SET",
]
