from enum import IntFlag


class Features(IntFlag):
    """
    Features that can be requested on a device.
    """

    EMPTY = 0
    # WebGPU features
    DEPTH_CLIP_CONTROL = 1 << 0
    DEPTH32FLOAT_STENCIL8 = 1 << 1
    TEXTURE_COMPRESSION_BC = 1 << 2
    TEXTURE_COMPRESSION_ETC2 = 1 << 3
    TEXTURE_COMPRESSION_ASTC = 1 << 4
    TIMESTAMP_QUERY = 1 << 5
    INDIRECT_FIRST_INSTANCE = 1 << 6
    SHADER_F16 = 1 << 7
    RG11B10UFLOAT_RENDERABLE = 1 << 8
    BGRA8UNORM_STORAGE = 1 << 9
    FLOAT32_FILTERABLE = 1 << 10
    CLIP_DISTANCES = 1 << 11
    DUAL_SOURCE_BLENDING = 1 << 12

    # native features
    PUSH_CONSTANTS = 1 << 16
    TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES = 1 << 17
    MULTI_DRAW_INDIRECT = 1 << 18
    MULTI_DRAW_INDIRECT_COUNT = 1 << 19
    VERTEX_WRITABLE_STORAGE = 1 << 20
    TEXTURE_BINDING_ARRAY = 1 << 21
    SAMPLED_TEXTURE_AND_STORAGE_BUFFER_ARRAY_NON_UNIFORM_INDEXING = 1 << 22
    PIPELINE_STATISTICS_QUERY = 1 << 23
    STORAGE_RESOURCE_BINDING_ARRAY = 1 << 24
    PARTIALLY_BOUND_BINDING_ARRAY = 1 << 25
    TEXTURE_FORMAT_16BIT_NORM = 1 << 26
    ADDRESS_MODE_CLAMP_TO_BORDER = 1 << 27
    ADDRESS_MODE_CLAMP_TO_ZERO = 1 << 28
    POLYGON_MODE_LINE = 1 << 29
    POLYGON_MODE_POINT = 1 << 30
    CONSERVATIVE_RASTERIZATION = 1 << 31
    VERTEX_ATTRIBUTE_64BIT = 1 << 32
    SUBGROUPS = 1 << 33
    SUBGROUP_SHUFFLE = 1 << 34
    SUBGROUP_VOTE = 1 << 35
    SUBGROUP_ARITHMETIC = 1 << 36
    SUBGROUP_QUAD = 1 << 37
    CLEAR_TEXTURE = 1 << 38
    RAY_TRACING = 1 << 39
    RAY_QUERY = 1 << 40
    RAY_HIT_VERTEX_RETURN = 1 << 41
    MESH_SHADER = 1 << 42
    COOPERATIVE_MATRIX = 1 << 43

    # Experimental aliases for compatibility
    EXPERIMENTAL_RAY_QUERY = RAY_QUERY
    EXPERIMENTAL_RAY_HIT_VERTEX_RETURN = RAY_HIT_VERTEX_RETURN
    EXPERIMENTAL_MESH_SHADER = MESH_SHADER
    EXPERIMENTAL_COOPERATIVE_MATRIX = COOPERATIVE_MATRIX

    TIMESTAMP_QUERY_INSIDE_PASSES = 1 << 44
    MAPPABLE_PRIMARY_BUFFERS = 1 << 45
    NATIVE_POWER_PREFERENCE = 1 << 46
    NATIVE_PRESENT_MODE = 1 << 47
    BUFFER_BINDING_ARRAY = 1 << 48
    SAMPLED_TEXTURE_ARRAY_NON_UNIFORM_INDEXING = 1 << 49
    STORAGE_TEXTURE_ARRAY_NON_UNIFORM_INDEXING = 1 << 50
    UNSIZED_BINDING_ARRAY = 1 << 51
    MULTI_VIEW = 1 << 52
    DEPTH_CLAMP = 1 << 53
    SHADER_INT64 = 1 << 54
    SHADER_INT16 = 1 << 55
    SHADER_PRIMITIVE_INDEX = 1 << 56
    SHADER_EARLY_DEPTH_TEST = 1 << 57
    SHADER_DEVICE_ADDRESS = 1 << 58
    SHADER_FLOAT64 = 1 << 59
    SHADER_ATOMIC_I64 = 1 << 60
    SHADER_ATOMIC_F32_ADD = 1 << 61
    SHADER_ATOMIC_F32_MIN_MAX = 1 << 62
    SHADER_ATOMIC_F64_ADD = 1 << 63
    SHADER_ATOMIC_F64_MIN_MAX = 1 << 64
    SPIRV_SHADER_PASSTHROUGH = 1 << 65
    MULTIVIEW_EXT = 1 << 66
