from enum import IntFlag

class Features(IntFlag):
    """
    Features that can be requested on a device.
    """
    EMPTY = 0
    # WebGPU features
    DEPTH_CLIP_CONTROL = 1 << 0
    DEPTH32FLOAT_STENCIL8 = 1 << 1
    TEXTURE_COMPRESSION_BC = 1 << 2
    TEXTURE_COMPRESSION_BC_SLICED_3D = 1 << 3
    TEXTURE_COMPRESSION_ETC2 = 1 << 4
    TEXTURE_COMPRESSION_ASTC = 1 << 5
    TEXTURE_COMPRESSION_ASTC_SLICED_3D = 1 << 6
    TIMESTAMP_QUERY = 1 << 7
    INDIRECT_FIRST_INSTANCE = 1 << 8
    SHADER_F16 = 1 << 9
    RG11B10UFLOAT_RENDERABLE = 1 << 10
    BGRA8UNORM_STORAGE = 1 << 11
    FLOAT32_FILTERABLE = 1 << 12
    # native features
    PUSH_CONSTANTS = 1 << 16
    TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES = 1 << 17
    MULTI_DRAW_INDIRECT = 1 << 18
    MULTI_DRAW_INDIRECT_COUNT = 1 << 19
    VERTEX_WRITABLE_STORAGE = 1 << 20
    TEXTURE_BINDING_ARRAY = 1 << 21
    SAMPLED_TEXTURE_AND_STORAGE_BUFFER_ARRAY_NON_UNIFORM_INDEXING = 1 << 22
    PIPELINE_STATISTICS_QUERY = 1 << 23
    STORAGE_RESOURCE_BINDING_ARRAY = 1 << 24
    PARTIALLY_BOUND_BINDING_ARRAY = 1 << 25
    TEXTURE_FORMAT_16BIT_NORM = 1 << 26
    ADDRESS_MODE_CLAMP_TO_BORDER = 1 << 27
    ADDRESS_MODE_CLAMP_TO_ZERO = 1 << 28
    # ... and so on
    
    MAPPED_AT_CREATION = 1 << 60 # Example of other flags
