from typing import Any, Protocol, TypeVar, Optional, List

T = TypeVar('T')

class Instance(Protocol):
    """HAL Instance trait."""
    def enumerate_adapters(self) -> List[Any]: ...
    def create_surface(self, display_handle: Any, window_handle: Any) -> Any: ...

class Adapter(Protocol):
    """HAL Adapter trait."""
    def open(self, features: Any, limits: Any) -> Any: ...
    def adapter_info(self) -> Any: ...

class Device(Protocol):
    """HAL Device trait."""
    def create_buffer(self, desc: Any) -> Any: ...
    def create_texture(self, desc: Any) -> Any: ...
    def create_shader_module(self, desc: Any, source: Any) -> Any: ...

class Surface(Protocol):
    """HAL Surface trait."""
    def configure(self, device: Any, config: Any) -> None: ...
    def unconfigure(self, device: Any) -> None: ...
    def acquire_texture(self, timeout: Optional[float]) -> Any: ...
    def discard_texture(self, texture: Any) -> None: ...

class Api(Protocol):
    """HAL Api trait."""
    Instance: Any
    Adapter: Any
    Device: Any
    Surface: Any
    
    def init(self) -> None: ...
